version: '3.3'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
    - .:/argalon  
    container_name: argalon-app
    restart: always
    
